# Generated by Django 4.1.3 on 2022-12-06 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("patient", "0002_patient_user"),
        ("appointment", "0003_alter_appointment_room"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="patient",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="patient.patient",
            ),
        ),
    ]
