# Generated by Django 4.1.3 on 2022-12-07 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0003_staff_user"),
        ("appointment", "0004_alter_appointment_patient"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="issued_staff",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="staff.staff",
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="room",
            field=models.CharField(max_length=7),
        ),
    ]
