# Generated by Django 4.1.3 on 2022-12-11 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("appointment", "0005_alter_appointment_issued_staff_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appointment",
            name="room",
        ),
    ]
