# Generated by Django 4.1.3 on 2022-11-08 06:03

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("patient", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="registration_date_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="patient",
            name="eid",
            field=models.CharField(
                max_length=18,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Emirates ID must be in format 111-1111-1111111-1",
                        regex="^(\\d{1,3}(-(\\d{1,4}(-(\\d{1,7}(-(\\d{1,1})?)?)?)?)?)?)$",
                    )
                ],
                verbose_name="Emirates ID",
            ),
        ),
    ]
