# Generated by Django 4.1.3 on 2022-11-15 23:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import new_life.validators
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("department", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=25)),
                ("number_of_staff", models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Staff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=50)),
                (
                    "profile_pic",
                    models.ImageField(
                        blank=True,
                        upload_to="profile_photo/staff/",
                        validators=[new_life.validators.validate_file_size],
                    ),
                ),
                ("date_of_birth", models.DateField()),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region="AE"
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")], max_length=1
                    ),
                ),
                (
                    "blood_group",
                    models.CharField(
                        choices=[
                            ("A+", "A+"),
                            ("A-", "A-"),
                            ("B+", "B+"),
                            ("B-", "B-"),
                            ("O+", "O+"),
                            ("O-", "O-"),
                            ("AB+", "AB+"),
                            ("AB-", "AB-"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "eid",
                    models.CharField(
                        max_length=18,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Emirates ID must be in format 111-1111-1111111-1",
                                regex="^(\\d{1,3}(-(\\d{1,4}(-(\\d{1,7}(-(\\d{1,1})?)?)?)?)?)?)$",
                            )
                        ],
                        verbose_name="Emirates ID",
                    ),
                ),
                (
                    "registration_date_time",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "working_hours",
                    models.CharField(
                        choices=[
                            ("Morning", "08:00-13:00"),
                            ("Noon", "13:00-18:00"),
                            ("Night", "18:00-00:00"),
                        ],
                        max_length=11,
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="department.department",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="staff.role"
                    ),
                ),
            ],
        ),
    ]
