# Generated by Django 4.1.3 on 2022-12-11 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0003_staff_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staff",
            name="email",
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
    ]
