# Generated by Django 4.1.3 on 2022-12-13 22:53

from django.db import migrations, models
import new_life.validators


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0004_alter_staff_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staff",
            name="profile_pic",
            field=models.ImageField(
                blank=True,
                default="profile_photo/profile_placeholder.jpg",
                upload_to="profile_photo/staff/",
                validators=[new_life.validators.validate_file_size],
            ),
        ),
    ]
