# Generated by Django 4.1.3 on 2022-11-15 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("department", "0001_initial"),
        ("doctor", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="blood_group",
            field=models.CharField(
                choices=[
                    ("A+", "A+"),
                    ("A-", "A-"),
                    ("B+", "B+"),
                    ("B-", "B-"),
                    ("O+", "O+"),
                    ("O-", "O-"),
                    ("AB+", "AB+"),
                    ("AB-", "AB-"),
                ],
                default="A+",
                max_length=3,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="doctor",
            name="email",
            field=models.EmailField(default="abc@xyz.com", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="doctor",
            name="working_hours",
            field=models.CharField(
                choices=[
                    ("Morning", "08:00-13:00"),
                    ("Noon", "13:00-18:00"),
                    ("Night", "18:00-00:00"),
                ],
                default="08:00-13:00",
                max_length=11,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="doctor",
            name="department",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="department.department"
            ),
        ),
        migrations.DeleteModel(
            name="Department",
        ),
    ]
