# Generated by Django 4.1.3 on 2022-11-16 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "doctor",
            "0002_doctor_blood_group_doctor_email_doctor_working_hours_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctor",
            name="working_hours",
            field=models.CharField(
                choices=[
                    ("08:00-13:00", "Morning"),
                    ("13:00-18:00", "Noon"),
                    ("18:00-00:00", "Night"),
                ],
                max_length=11,
            ),
        ),
    ]
