# Generated by Django 4.1.3 on 2022-11-16 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0004_doctor_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="user_name",
            field=models.CharField(default="damnbro", max_length=15),
            preserve_default=False,
        ),
    ]
