# Generated by Django 4.1.3 on 2022-12-02 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0007_remove_doctor_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="password",
            field=models.CharField(default="password", max_length=50),
            preserve_default=False,
        ),
    ]
