# Generated by Django 4.1.3 on 2022-12-02 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0008_doctor_password"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="doctor",
            name="password",
        ),
    ]
