# Generated by Django 4.1.3 on 2022-12-03 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0009_remove_doctor_password"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="doctor",
            name="user_name",
        ),
    ]
