# Generated by Django 4.1.3 on 2022-12-05 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("appointment", "0002_alter_appointment_issued_staff"),
        ("doctor", "0010_remove_doctor_user_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="appointments",
            field=models.ForeignKey(
                blank=True,
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="doc_appointments",
                to="appointment.appointment",
            ),
            preserve_default=False,
        ),
    ]
