# Generated by Django 4.1.3 on 2022-12-11 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0012_remove_doctor_appointments"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="room",
            field=models.CharField(default="A:2-15", max_length=10),
            preserve_default=False,
        ),
    ]
