# Generated by Django 4.1.3 on 2022-12-11 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0013_doctor_room"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctor",
            name="email",
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
    ]
