# Generated by Django 4.1.3 on 2022-12-12 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("patient_utils", "0002_prescription_medicalreport_prescription"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medicalreport",
            name="allergies",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name="medicalreport",
            name="lab",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="patient_utils.lab",
            ),
        ),
        migrations.AlterField(
            model_name="medicalreport",
            name="xray",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="patient_utils.xray",
            ),
        ),
    ]
