# Generated by Django 4.1.3 on 2022-12-12 14:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("patient_utils", "0003_alter_medicalreport_allergies_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prescription",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
