# Generated by Django 4.1.3 on 2022-12-12 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("appointment", "0006_remove_appointment_room"),
        ("patient_utils", "0004_alter_prescription_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="medicalreport",
            name="appointment",
        ),
        migrations.AddField(
            model_name="prescription",
            name="appointment",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="appointment.appointment",
            ),
            preserve_default=False,
        ),
    ]
