# Generated by Django 4.1.3 on 2022-12-12 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("patient_utils", "0005_remove_medicalreport_appointment_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="prescription",
            name="date",
        ),
    ]
