# Generated by Django 4.1.3 on 2022-12-12 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("patient_utils", "0006_remove_prescription_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medicalreport",
            name="prescription",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="patient_utils.prescription",
            ),
        ),
    ]
