# Generated by Django 4.1.3 on 2022-11-08 07:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("patient", "0002_patient_registration_date_time_alter_patient_eid"),
    ]

    operations = [
        migrations.RenameField(
            model_name="patient",
            old_name="name",
            new_name="full_name",
        ),
        migrations.AddField(
            model_name="patient",
            name="profile_pic",
            field=models.FileField(default=django.utils.timezone.now, upload_to=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="patient",
            name="registration_date_time",
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
