# Generated by Django 4.1.3 on 2022-11-13 17:45

from django.db import migrations, models
import patient.validators


class Migration(migrations.Migration):

    dependencies = [
        ("patient", "0003_rename_name_patient_full_name_patient_profile_pic_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="address",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="patient",
            name="blood_group",
            field=models.CharField(
                choices=[
                    ("A+", "A+"),
                    ("A-", "A-"),
                    ("B+", "B+"),
                    ("B-", "B-"),
                    ("O+", "O+"),
                    ("O-", "O-"),
                    ("AB+", "AB+"),
                    ("AB-", "AB-"),
                ],
                default="AB+",
                max_length=3,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="patient",
            name="email",
            field=models.EmailField(default="xyz@abc.com", max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="patient",
            name="profile_pic",
            field=models.ImageField(
                blank=True,
                upload_to="profile_photo/patient/",
                validators=[patient.validators.validate_file_size],
            ),
        ),
    ]
